name: Test 

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
      - '*'
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: make
